CREATE DATABASE LOGIN_SYSTEM
DEFAULT CHARACTER SET utf8
COLLATE utf8_hungarian_ci;

DROP TABLE IF EXISTS LOGIN_SYSTEM.USERS;
CREATE TABLE USERS (
    `UserId` INT AUTO_INCREMENT,
    `Username` VARCHAR(51) NOT NULL DEFAULT "", 
    `Email` VARCHAR(255) NOT NULL DEFAULT "",
    `PswHash` VARCHAR(255) NOT NULL DEFAULT "",
    `CreatedAt` VARCHAR(255) NOT NULL DEFAULT "",
    `Active` BOOLEAN NOT NULL DEFAULT FALSE,
    `VerHash` VARCHAR(255) NOT NULL DEFAULT "",
    `Timeout` VARCHAR(255) NOT NULL DEFAULT "",
    PRIMARY KEY(`UserId`)
);


DROP TABLE IF EXISTS LOGIN_SYSTEM.USER_EMAIL_VER_HASH;
CREATE TABLE USER_EMAIL_VER_HASH (
    `Username` VARCHAR(255) NOT NULL DEFAULT "",
    `Email` VARCHAR(255) NOT NULL DEFAULT "",
    `VerHash` VARCHAR(255) NOT NULL DEFAULT "",
    `Timeout` VARCHAR(255) NOT NULL DEFAULT ""
);